<<<<<<< HEAD
# Generated by Django 2.2.7 on 2020-01-13 13:55
=======
# Generated by Django 2.2.7 on 2020-01-13 19:22
>>>>>>> Development

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'Employee')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('departments', models.PositiveSmallIntegerField(choices=[(1, 'Human Resource'), (2, 'Inventory'), (3, 'Finance'), (4, 'Marketing'), (5, 'Information Technology')])),
=======
                ('department', models.PositiveSmallIntegerField(choices=[(1, 'Human Resource'), (2, 'Inventory'), (3, 'Finance'), (4, 'Marketing'), (5, 'Information Technology')], null=True)),
>>>>>>> Development
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
