# Generated by Django 2.2.7 on 2020-01-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
