# Generated by Django 2.2.7 on 2020-01-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='update_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Human Resource'), (2, 'Marketing'), (3, 'Information Technology'), (4, 'Finance'), (5, 'Marketing'), (6, 'General')], null=True),
        ),
    ]
