# Generated by Django 2.2.7 on 2020-01-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='departments',
            new_name='department',
        ),
    ]
