# Generated by Django 2.2.7 on 2020-01-28 07:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='department',
            field=models.PositiveSmallIntegerField(choices=[(1, 'General'), (2, 'Human Resource'), (3, 'Information_technology'), (4, 'Inventory'), (5, 'Marketing'), (6, 'Finance')], null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='updates',
            name='update',
            field=tinymce.models.HTMLField(),
        ),
    ]
