# Generated by Django 2.2.7 on 2020-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
