# Generated by Django 2.2.7 on 2020-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_updates_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.TextField(),
        ),
    ]
