# Generated by Django 2.2.7 on 2020-01-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_updates_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='image',
        ),
    ]
