# Generated by Django 2.2.7 on 2020-01-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20200113_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Human Resource'), (2, 'Inventory'), (3, 'Finance'), (4, 'Marketing'), (5, 'Information Technology')], null=True),
        ),
    ]
