# Generated by Django 2.2 on 2020-01-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_auto_20200114_0900'),
        ('intranet', '0002_comments_profile_updates'),
    ]

    operations = [
    ]
