# Generated by Django 2.2.7 on 2020-01-19 13:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_auto_20200117_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='update',
            field=tinymce.models.HTMLField(),
        ),
    ]
