# Generated by Django 2.2.7 on 2020-01-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_auto_20200116_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
