# Generated by Django 2.2.7 on 2020-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_auto_20200119_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
